export const LOGIN_USER_SUCCESSFUL = "LOGIN_USER";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const LOGOUT_USER = "LOGOUT_USER";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_MODAL = "OPEN_MODAL";

export const OPEN_SNACKBAR = "OPEN_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";

export const INITIAL_LOADING = "INITIAL_LOADING";

export const UPLOAD_AVATAR = "UPLOAD_AVATAR";
export const GET_ME_SUCCESSFULLY = "GET_ME_SUCCESSFULLY";
export const GET_ME_FAILED = "GET_ME_FAILED";